
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.1-2-g21f58cc'
version_full = '21f58ccc9a29ee82faf0924ea03f39b3c91e43ee'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

