# http://travis-ci.org/#!/jaraco/keyring

language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.2
  - 3.3

script:
  - if [[ ${TRAVIS_PYTHON_VERSION:0:1} == '3' ]]; then OPTS="build/lib"; fi
  - python setup.py ptr --addopts="-rs -v $OPTS"
