
/*
 *****************************************************************************
 **       This file was autogenerated from a template  DO NOT EDIT!!!!      **
 **       Changes should be made to the original source (.src) file         **
 **       Produced by conv_template.py                                      **
 *****************************************************************************
 */

#line 1
/* -*- c -*- */

/*
    Taken from numpy/core/src/umath/loops.c.src
    date: 9/11/2012
    git hash: 75b8119f8145ab08a436ecfd7de868c6c6ba8f6d
*/
#include "export.h"

#line 14

DL_EXPORT(npy_byte)
npy_babs(npy_byte in)
{
    return (in >= 0) ? in : -in;
}

#line 14

DL_EXPORT(npy_short)
npy_sabs(npy_short in)
{
    return (in >= 0) ? in : -in;
}

#line 14

DL_EXPORT(npy_int)
npy_abs(npy_int in)
{
    return (in >= 0) ? in : -in;
}

#line 14

DL_EXPORT(npy_long)
npy_labs(npy_long in)
{
    return (in >= 0) ? in : -in;
}

#line 14

DL_EXPORT(npy_longlong)
npy_llabs(npy_longlong in)
{
    return (in >= 0) ? in : -in;
}


