__version__ = "0.0.4"
__git_commiter_name__ = "Itai Shirav"
__git_commiter_email__ = "itais@infinidat.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '69431e1868ef3a21214024785626f3d54ee1378d'
__git_head_subject__ = 'added optional prefix to Command'
__git_head_message__ = ''
__git_dirty_diff__ = ''