
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.20'
version_full = 'b5a1ad64d60679c956a536cd6d6d9843744e75e5'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

