__version__ = "0.3.29"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'b7fa58a16f4371fd03db446f4e255afb7bf7a971'
__git_head_subject__ = 'support minimal-packages'
__git_head_message__ = ''
__git_dirty_diff__ = ''