# Autogenerated by Astropy-affiliated package montage_wrapper's setup.py on 2013-11-02 16:47:59.735820

from astropy.version_helpers import update_git_devstr, get_git_devstr

_last_generated_version = '0.9.7'

version = update_git_devstr(_last_generated_version)
githash = get_git_devstr(sha=True, show_warning=False)

major = 0
minor = 9
bugfix = 7

release = True
debug = False

try:
    from .utils._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
