from setuptools import setup
setup(
    name='pytest-cache',
    description='pytest plugin with mechanisms for caching across test runs',
    long_description=open("README.rst").read(),
    version='1.0',
    author='Holger Krekel',
    author_email='holger.krekel@gmail.com',
    url='http://bitbucket.org/hpk42/pytest-cache/',
    py_modules=['pytest_cache'],
    entry_points={'pytest11': ['cacheprovider = pytest_cache']},
    install_requires=['pytest>=2.2', 'execnet>=1.1.dev1', ],
    classifiers=[
            'Development Status :: 3 - Alpha',
            'Intended Audience :: Developers',
            'License :: OSI Approved :: GNU General Public License (GPL)',
            'Operating System :: POSIX',
            'Operating System :: Microsoft :: Windows',
            'Operating System :: MacOS :: MacOS X',
            'Topic :: Software Development :: Testing',
            'Topic :: Software Development :: Libraries',
            'Topic :: Utilities',
            'Programming Language :: Python',
            'Programming Language :: Python :: 3'],
)
