language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install liblapack-dev gfortran libblas-dev
install:
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install Cython
  - python setup.py build_ext --inplace
script:
  - nosetests -s pymc/tests/