language: python
python: "2.7"
services:
- redis
#addons:
#  sauce_connect:
#  - username: $SAUCE_USERNAME
#  - access_key: $SAUCE_ACCESS_KEY
install:
- virtualenv test-env --no-setuptools
- mkdir -p buildout-cache/downloads
- test-env/bin/python bootstrap.py -c travis.cfg
- bin/buildout -N -t 3 -c travis.cfg
#before_script:
#- gem install travis-artifacts
#after_script:
#- travis-artifacts upload --path parts/test
script: bin/test
#env:
#  global:
#  - ARTIFACTS_S3_BUCKET=example.product
#  - ROBOT_BUILD_NUMBER=travis-$TRAVIS_BUILD_NUMBER
#  - ROBOT_REMOTE_URL=http://$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com:80/wd/hub
#  matrix:
#  - ROBOT_BROWSER=firefox ROBOT_DESIRED_CAPABILITIES=tunnel-identifier:$TRAVIS_JOB_NUMBER
