language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - "pip install -r requirements-full.txt --use-mirrors"
  - "pip install flake8 freezegun --use-mirrors"
  - "pip install . --use-mirrors"
# We run magic, tests, nikola (to see if the command is executable) and flake8.
script:
  - nosetests --with-coverage --cover-package=nikola --with-doctest --doctest-options=+NORMALIZE_WHITESPACE
  - nikola help
  - "flake8 --ignore=E501 ."
after_success:
  - coveralls
