
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.19'
version_full = 'd3a8d0e490bbb217680fab7a941e9fe5aea93a8d'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

