language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - pip install -r requirements.txt
  - pip install unittest2 || true

script: coverage run $(which nose2)

after_success:
  - coveralls

notifications:
    irc: "irc.oftc.net#yaybu"
    on_success: change
    on_failure: always

