language: python
python:
    - 2.6
    - 2.7
install:
    - pip install -e .
    - pip install zope.testrunner coverage coveralls
script:
    - coverage run --source=zodbbrowser -m zope.testrunner.__init__ --test-path=src --tests-pattern='^f?tests$'
after_success:
    - coveralls
notifications:
    email: false
