
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.2.1'
version_full = 'eb668b3f0040bd7d2a239f7152ad2c5b706e9ece'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

