__version__ = "0.4.13"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'fc45ba6025d7e82c9a5127dabafb2f10b773bb0f'
__git_head_subject__ = 'fixing tests'
__git_head_message__ = ''
__git_dirty_diff__ = ''