language: python
python:
  - 2.6
  - 2.7
install:
  - python setup.py install
  - pip install coverage
script:
  - nosetests -v --with-coverage --cover-tests --cover-package=noseselecttests noseselecttests/tests.py
