#
# This is the classic theme's configuation
#

name = "classic"  # theme's name

[author]  # theme's author
name = "hit9"
url = "http://hit9.org"

# There can be more vars, for example, twitter, linkedin ...,
# blog user can reset these configurations in '/config.toml'.

[vars]

github = "hit9"  # blogger's github username
