"""empty message

Revision ID: 3876f3c32a4a
Revises: None
Create Date: 2012-10-13 03:53:18.924283

"""

# revision identifiers, used by Alembic.
revision = '3876f3c32a4a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worklog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Enum('start', 'end', 'resume'), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worklog')
    ### end Alembic commands ###
