__version__ = "0.4.16"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(detached from v0.4.16)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '1b47da3f9b8278c46d9678b18af2abfb480ae1f3'
__git_head_subject__ = 'TRIVIAL fix hard_install'
__git_head_message__ = ''
__git_dirty_diff__ = ''