
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.11'
version_full = '6ba656f78d98186c5303e5f72b224648ea4771eb'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

