language: python
python:
  - 3.3

install:
  - pip install coveralls --use-mirrors
  - python setup.py develop --allow-hosts='pypi.python.org'

script:
  coverage run --source=aiohttp setup.py test
after_success:
  coveralls
