__version__ = "0.3.26"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'ecdea9f21dd0ed4c9c24dd9215bd9ce47b2f04a3'
__git_head_subject__ = 'Finished release v0.3.26.'
__git_head_message__ = ''
__git_dirty_diff__ = ''