
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.0'
version_full = '8f8fe5483d95a3cb3a340c24de419c3b410bfa8f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

