
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.9'
version_full = 'c09c7e61c4e44a3bab0ab4e73a8cee20824bf1fd'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

