
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.2'
version_full = 'bf74c7720808ae4a0a94ea80439bea08e1441acd'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

