
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.4'
version_full = '804de7641454677647a88b8650592e0ba415859f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

