language: python
python:
  - 2.7
env:
  - PLONE_VERSION=4.3
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - sed -ie "s#travis-4.3.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - git clone git://github.com/plone/plone.app.contenttypes.git
  - git clone git://github.com/plone/plone.app.vocabularies.git
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -q
script:
  - bin/flake8 setup.py
  - bin/flake8 plone
  - bin/test -vvv
