
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.2-5-g9568093'
version_full = '9568093138c85212e15d50ade5d5fc7dcec9ff6e'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

