__version__ = "0.1.1"
__git_commiter_name__ = "Tal Yalon"
__git_commiter_email__ = "tal.yalon@gmail.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '1024341155343b19e187f428832cd45fb033bbad'
__git_head_subject__ = 'Finished release v0.1.1.'
__git_head_message__ = ''
__git_dirty_diff__ = ''