
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.1.3-1-gc837b73'
version_full = 'c837b73e252835c3ceaa19049c4d9693e49ef5e2'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

