# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QSupervisorControl/data/configuration.ui'
#
# Created: Sat Feb  2 01:10:00 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(545, 321)
        Form.setMinimumSize(QtCore.QSize(545, 321))
        Form.setMaximumSize(QtCore.QSize(545, 321))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(4, 0, -1, 2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(Form)
        self.frame.setMinimumSize(QtCore.QSize(0, 65))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.txtPath = QtGui.QLineEdit(self.frame)
        self.txtPath.setGeometry(QtCore.QRect(10, 30, 470, 30))
        self.txtPath.setMinimumSize(QtCore.QSize(0, 30))
        self.txtPath.setMaximumSize(QtCore.QSize(16777215, 30))
        self.txtPath.setObjectName(_fromUtf8("txtPath"))
        self.bntSearchProject = QtGui.QToolButton(self.frame)
        self.bntSearchProject.setGeometry(QtCore.QRect(490, 30, 35, 30))
        self.bntSearchProject.setMinimumSize(QtCore.QSize(35, 30))
        self.bntSearchProject.setObjectName(_fromUtf8("bntSearchProject"))
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(Form)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 65))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.bntSearchReloadFile = QtGui.QToolButton(self.frame_2)
        self.bntSearchReloadFile.setGeometry(QtCore.QRect(490, 30, 35, 30))
        self.bntSearchReloadFile.setMinimumSize(QtCore.QSize(35, 30))
        self.bntSearchReloadFile.setObjectName(_fromUtf8("bntSearchReloadFile"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.txtTouchFile = QtGui.QLineEdit(self.frame_2)
        self.txtTouchFile.setGeometry(QtCore.QRect(10, 30, 470, 30))
        self.txtTouchFile.setMinimumSize(QtCore.QSize(0, 30))
        self.txtTouchFile.setMaximumSize(QtCore.QSize(16777215, 30))
        self.txtTouchFile.setObjectName(_fromUtf8("txtTouchFile"))
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(Form)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 65))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.bntSearchLogFile = QtGui.QToolButton(self.frame_3)
        self.bntSearchLogFile.setGeometry(QtCore.QRect(490, 30, 35, 30))
        self.bntSearchLogFile.setMinimumSize(QtCore.QSize(35, 30))
        self.bntSearchLogFile.setObjectName(_fromUtf8("bntSearchLogFile"))
        self.label_3 = QtGui.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.txtLogFile = QtGui.QLineEdit(self.frame_3)
        self.txtLogFile.setGeometry(QtCore.QRect(10, 30, 470, 30))
        self.txtLogFile.setMinimumSize(QtCore.QSize(0, 30))
        self.txtLogFile.setMaximumSize(QtCore.QSize(16777215, 30))
        self.txtLogFile.setObjectName(_fromUtf8("txtLogFile"))
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_5 = QtGui.QFrame(Form)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 65))
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.txtMonitorPattern = QtGui.QLineEdit(self.frame_5)
        self.txtMonitorPattern.setGeometry(QtCore.QRect(10, 30, 515, 30))
        self.txtMonitorPattern.setMinimumSize(QtCore.QSize(0, 30))
        self.txtMonitorPattern.setMaximumSize(QtCore.QSize(16777215, 30))
        self.txtMonitorPattern.setObjectName(_fromUtf8("txtMonitorPattern"))
        self.label_4 = QtGui.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 221, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_4 = QtGui.QFrame(Form)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setContentsMargins(-1, -1, 4, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.bntStore = QtGui.QPushButton(self.frame_4)
        self.bntStore.setMinimumSize(QtCore.QSize(0, 35))
        self.bntStore.setObjectName(_fromUtf8("bntStore"))
        self.horizontalLayout.addWidget(self.bntStore)
        self.bntCancel = QtGui.QPushButton(self.frame_4)
        self.bntCancel.setMinimumSize(QtCore.QSize(0, 35))
        self.bntCancel.setObjectName(_fromUtf8("bntCancel"))
        self.horizontalLayout.addWidget(self.bntCancel)
        self.verticalLayout.addWidget(self.frame_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.txtPath, self.bntSearchProject)
        Form.setTabOrder(self.bntSearchProject, self.txtTouchFile)
        Form.setTabOrder(self.txtTouchFile, self.bntSearchReloadFile)
        Form.setTabOrder(self.bntSearchReloadFile, self.txtLogFile)
        Form.setTabOrder(self.txtLogFile, self.bntSearchLogFile)
        Form.setTabOrder(self.bntSearchLogFile, self.txtMonitorPattern)
        Form.setTabOrder(self.txtMonitorPattern, self.bntStore)
        Form.setTabOrder(self.bntStore, self.bntCancel)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Configuração de Monitoramento", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Diretório do Projeto", None, QtGui.QApplication.UnicodeUTF8))
        self.bntSearchProject.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.bntSearchReloadFile.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Arquivo de Touche Reload", None, QtGui.QApplication.UnicodeUTF8))
        self.bntSearchLogFile.setText(QtGui.QApplication.translate("Form", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Arquivo de Logs", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Expressão regular para filtrar arquivos", None, QtGui.QApplication.UnicodeUTF8))
        self.bntStore.setText(QtGui.QApplication.translate("Form", "Gravar", None, QtGui.QApplication.UnicodeUTF8))
        self.bntCancel.setText(QtGui.QApplication.translate("Form", "Fechar", None, QtGui.QApplication.UnicodeUTF8))

