hg rm lino\sandbox\debts\locale
hg rm lino\modlib\contacts\locale
hg rm lino\modlib\countries\locale
hg rm lino\modlib\finan\locale
hg rm lino\modlib\ledger\locale
hg rm lino\modlib\links\locale
hg rm lino\modlib\notes\locale
hg rm lino\modlib\products\locale
hg rm lino\modlib\sales\locale
hg rm lino\modlib\uploads\locale
hg rm lino\modlib\properties\locale
hg rm lino\modlib\users\locale
hg rm lino\modlib\thirds\locale
hg rm lino\modlib\cal\locale
hg rm lino\modlib\outbox\locale
hg rm lino\modlib\postings\locale
hg rm lino\modlib\accounts\locale
hg rm lino\modlib\vat\locale
hg rm lino\modlib\households\locale
hg rm lino\modlib\about\locale
hg rm lino\modlib\concepts\locale
hg rm lino\modlib\partners\locale
hg rm lino\modlib\declarations\locale
hg rm lino\modlib\events\locale
hg rm lino\projects\cosi\locale
hg rm lino\projects\igen\locale
