language: python
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - pypy
install:
    - pip install mock coverage coveralls --use-mirrors
    - pip install . --use-mirrors
script:
    - coverage run --source=src/restview setup.py test -q
after_script:
    - coveralls
notifications:
    email: false
