// Generated by CoffeeScript 1.4.0
(function() {
  var Feedback;

  Feedback = (function() {

    function Feedback() {}

    Feedback.prototype.configure = function(enabled, os, version, edition) {
      this.enabled = enabled;
      this.os = os;
      this.version = version;
      this.edition = edition;
    };

    Feedback.prototype.emit = function(evt, params) {
      if (this.enabled) {
        if (params == null) {
          params = {};
        }
        params.os = this.os;
        params.version = this.version;
        params.edition = this.edition;
        return mixpanel.track(evt, params);
      }
    };

    return Feedback;

  })();

  window.Feedback = new Feedback();

}).call(this);
