
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.6'
version_full = 'ae80ea1f0a748c2746026bd1a17815d786722b84'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

