
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.0.1'
version_full = 'd0166fbd4004ce5d8e709d54814c28750098bfac'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

