DEFAULT: &default
    DEBUG: False
    TESTING: False
    DATABASE_URI: None

DEV: &development
    <<: *default
    DEBUG: True
    SQLALCHEMY_DATABASE_URI: "mysql://root:1234@127.0.0.1/dev_db"

TEST: &testing
    <<: *default
    TESTING: True
    DATABASE_URI: "mysql://root:1234@127.0.0.1/test_db"

