__version__ = "0.6.9"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'adec3163d8c73b1fd2321a791ea833747e5be2ea'
__git_head_subject__ = 'Finished release v0.6.9.'
__git_head_message__ = ''
__git_dirty_diff__ = ''