language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy
install:
  - pip install -r tools/test-requires --use-mirrors
  - pip install coveralls
  - python setup.py install
script: nosetests
after_success: coveralls
notifications:
  email:
    - kurt.griffiths@rackspace.com
