
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.5-3-ge021b42'
version_full = 'e021b4236ffce9dfb6e302971e8d2f460b601bf3'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

