__version__ = "0.0.10"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '108c8f0e2eff829847c391f1d01c2c4c9ff6f0eb'
__git_head_subject__ = 'Finished release v0.0.10.'
__git_head_message__ = ''
__git_dirty_diff__ = ''