__version__ = "0.1.3.post6.g2e44345"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = 'develop'
__git_remote_tracking_branch__ = 'origin/develop'
__git_remote_url__ = 'git@infinigit.infinidat.com:/host/infi-jira-cli.git'
__git_head_hash__ = '2e44345df2768f1728480eed4c06fd3f9fdbcfb9'
__git_head_subject__ = 'Unfreezing dependencies'
__git_head_message__ = ''
__git_dirty_diff__ = ''