__version__ = "0.1.4"
__git_commiter_name__ = "Tal Yalon"
__git_commiter_email__ = "tal.yalon@gmail.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'ebe767390cc2936edffaca497ed0a1b02fe07019'
__git_head_subject__ = 'Finished release v0.1.4.'
__git_head_message__ = ''
__git_dirty_diff__ = ''