
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.1-10-gdf9c43e'
version_full = 'df9c43ec8d239595a40602b0e94125484a2144b2'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

