# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/leap/bitmask/gui/ui/mainwindow.ui'
#
# Created: Fri Aug 30 20:09:03 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(429, 579)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/mask-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        MainWindow.setIconSize(QtCore.QSize(128, 128))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 1, 1, 1)
        self.lblNewUpdates = QtGui.QLabel(self.centralwidget)
        self.lblNewUpdates.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblNewUpdates.setObjectName("lblNewUpdates")
        self.gridLayout_4.addWidget(self.lblNewUpdates, 2, 1, 1, 1)
        self.btnMore = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMore.sizePolicy().hasHeightForWidth())
        self.btnMore.setSizePolicy(sizePolicy)
        self.btnMore.setFlat(True)
        self.btnMore.setObjectName("btnMore")
        self.gridLayout_4.addWidget(self.btnMore, 2, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 2, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 0, 1, 5)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 6, 2, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtGui.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.gridLayout_2 = QtGui.QGridLayout(self.loginPage)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.loginLayout = QtGui.QHBoxLayout()
        self.loginLayout.setObjectName("loginLayout")
        self.gridLayout_2.addLayout(self.loginLayout, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.loginPage)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.statusLayout = QtGui.QVBoxLayout()
        self.statusLayout.setObjectName("statusLayout")
        self.gridLayout_3.addLayout(self.statusLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 10, 0, 1, 5)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/mask-launcher.png"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 2, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 7, 3, 1, 2)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 17, 2, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 7, 0, 1, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnPreferences = QtGui.QPushButton(self.centralwidget)
        self.btnPreferences.setEnabled(False)
        self.btnPreferences.setObjectName("btnPreferences")
        self.horizontalLayout.addWidget(self.btnPreferences)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.btnShowLog = QtGui.QPushButton(self.centralwidget)
        self.btnShowLog.setCheckable(True)
        self.btnShowLog.setChecked(False)
        self.btnShowLog.setFlat(True)
        self.btnShowLog.setObjectName("btnShowLog")
        self.horizontalLayout.addWidget(self.btnShowLog)
        self.gridLayout.addLayout(self.horizontalLayout, 18, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 429, 21))
        self.menubar.setObjectName("menubar")
        self.menuSession = QtGui.QMenu(self.menubar)
        self.menuSession.setObjectName("menuSession")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_log_out = QtGui.QAction(MainWindow)
        self.action_log_out.setObjectName("action_log_out")
        self.action_quit = QtGui.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.action_about_leap = QtGui.QAction(MainWindow)
        self.action_about_leap.setObjectName("action_about_leap")
        self.action_help = QtGui.QAction(MainWindow)
        self.action_help.setObjectName("action_help")
        self.action_wizard = QtGui.QAction(MainWindow)
        self.action_wizard.setObjectName("action_wizard")
        self.action_show_logs = QtGui.QAction(MainWindow)
        self.action_show_logs.setObjectName("action_show_logs")
        self.menuSession.addAction(self.action_log_out)
        self.menuSession.addSeparator()
        self.menuSession.addAction(self.action_quit)
        self.menuHelp.addAction(self.action_help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.action_about_leap)
        self.menubar.addAction(self.menuSession.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Bitmask", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNewUpdates.setText(QtGui.QApplication.translate("MainWindow", "There are new updates available, please restart.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnMore.setText(QtGui.QApplication.translate("MainWindow", "More...", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPreferences.setText(QtGui.QApplication.translate("MainWindow", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.btnShowLog.setText(QtGui.QApplication.translate("MainWindow", "Show Log", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSession.setTitle(QtGui.QApplication.translate("MainWindow", "&Session", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_log_out.setText(QtGui.QApplication.translate("MainWindow", "Log &out", None, QtGui.QApplication.UnicodeUTF8))
        self.action_quit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_about_leap.setText(QtGui.QApplication.translate("MainWindow", "About &Bitmask", None, QtGui.QApplication.UnicodeUTF8))
        self.action_help.setText(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_wizard.setText(QtGui.QApplication.translate("MainWindow", "&Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.action_show_logs.setText(QtGui.QApplication.translate("MainWindow", "Show &logs", None, QtGui.QApplication.UnicodeUTF8))

import mainwindow_rc
import locale_rc
