# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/leap/bitmask/gui/ui/preferences.ui'
#
# Created: Fri Aug 30 20:09:03 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(451, 267)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/mask-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Preferences.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(Preferences)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbPasswordChange = QtGui.QGroupBox(Preferences)
        self.gbPasswordChange.setObjectName("gbPasswordChange")
        self.formLayout = QtGui.QFormLayout(self.gbPasswordChange)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.lblCurrentPassword = QtGui.QLabel(self.gbPasswordChange)
        self.lblCurrentPassword.setObjectName("lblCurrentPassword")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblCurrentPassword)
        self.leCurrentPassword = QtGui.QLineEdit(self.gbPasswordChange)
        self.leCurrentPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.leCurrentPassword.setObjectName("leCurrentPassword")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.leCurrentPassword)
        self.lblNewPassword = QtGui.QLabel(self.gbPasswordChange)
        self.lblNewPassword.setObjectName("lblNewPassword")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblNewPassword)
        self.leNewPassword = QtGui.QLineEdit(self.gbPasswordChange)
        self.leNewPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.leNewPassword.setObjectName("leNewPassword")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.leNewPassword)
        self.lblNewPassword2 = QtGui.QLabel(self.gbPasswordChange)
        self.lblNewPassword2.setObjectName("lblNewPassword2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblNewPassword2)
        self.leNewPassword2 = QtGui.QLineEdit(self.gbPasswordChange)
        self.leNewPassword2.setEchoMode(QtGui.QLineEdit.Password)
        self.leNewPassword2.setObjectName("leNewPassword2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.leNewPassword2)
        self.pbChangePassword = QtGui.QPushButton(self.gbPasswordChange)
        self.pbChangePassword.setObjectName("pbChangePassword")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.pbChangePassword)
        self.lblPasswordChangeStatus = QtGui.QLabel(self.gbPasswordChange)
        self.lblPasswordChangeStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPasswordChangeStatus.setObjectName("lblPasswordChangeStatus")
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.lblPasswordChangeStatus)
        self.verticalLayout.addWidget(self.gbPasswordChange)
        self.gbGatewaySelector = QtGui.QGroupBox(Preferences)
        self.gbGatewaySelector.setEnabled(False)
        self.gbGatewaySelector.setCheckable(False)
        self.gbGatewaySelector.setObjectName("gbGatewaySelector")
        self.gridLayout = QtGui.QGridLayout(self.gbGatewaySelector)
        self.gridLayout.setObjectName("gridLayout")
        self.lblSelectProvider = QtGui.QLabel(self.gbGatewaySelector)
        self.lblSelectProvider.setObjectName("lblSelectProvider")
        self.gridLayout.addWidget(self.lblSelectProvider, 0, 0, 1, 1)
        self.cbProviders = QtGui.QComboBox(self.gbGatewaySelector)
        self.cbProviders.setObjectName("cbProviders")
        self.cbProviders.addItem("")
        self.gridLayout.addWidget(self.cbProviders, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.gbGatewaySelector)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.gbGatewaySelector)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.gbGatewaySelector)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.lblCurrentPassword.setBuddy(self.leCurrentPassword)
        self.lblNewPassword.setBuddy(self.leNewPassword)
        self.lblNewPassword2.setBuddy(self.leNewPassword2)
        self.lblSelectProvider.setBuddy(self.cbProviders)

        self.retranslateUi(Preferences)
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        Preferences.setWindowTitle(QtGui.QApplication.translate("Preferences", "Preferences", None, QtGui.QApplication.UnicodeUTF8))
        self.gbPasswordChange.setTitle(QtGui.QApplication.translate("Preferences", "Password Change", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCurrentPassword.setText(QtGui.QApplication.translate("Preferences", "&Current password:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNewPassword.setText(QtGui.QApplication.translate("Preferences", "&New password:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblNewPassword2.setText(QtGui.QApplication.translate("Preferences", "&Re-enter new password:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbChangePassword.setText(QtGui.QApplication.translate("Preferences", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPasswordChangeStatus.setText(QtGui.QApplication.translate("Preferences", "<Password change status>", None, QtGui.QApplication.UnicodeUTF8))
        self.gbGatewaySelector.setTitle(QtGui.QApplication.translate("Preferences", "Select gateway for provider", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSelectProvider.setText(QtGui.QApplication.translate("Preferences", "&Select provider:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbProviders.setItemText(0, QtGui.QApplication.translate("Preferences", "<Select provider>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Preferences", "Select gateway:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Preferences", "Automatic", None, QtGui.QApplication.UnicodeUTF8))

import mainwindow_rc
