---
install:
- sed -ie "s#travis-4.x.cfg#travis-$PLONE.x.cfg#" travis.cfg
- mkdir -p buildout-cache/downloads
- python bootstrap.py -c travis.cfg
- bin/buildout -c travis.cfg -N -q -t 10
env:
  global:
  - secure: |-
      StcHqDHnHo5Dg84lFKMRTDb+G1+PGkO86NGpAblhR+Kda1ZkJ/i9Ml3qaQQ+
      pbuo8qwcs8X60yih5fCCNQh6imbYc/tVLdh2x2CargobUCt3L3IWbVraG32U
      Nst0/1pvH1jEfz/qkaoTn8phKaXthjiIhj3auwg+jHsK2x7sZIE=
  - secure: |-
      PhW4f8CM1W7MfA6VmQHlS0prCyMH/tWm49QeOSPEMIqORn+Z0V4Iwv6PKrDw
      iXHPAtOGrWAJySUbbflCOX7orpIXF/4jW0IpDKeddDzZvP/FWEl/QahZtgib
      8Zo5BoQWClEz5ykB7jGl2AkyJSUUFVuhEKuLGiuTsJIfbs+gb5o=
  matrix:
  - PLONE=4.0
  - PLONE=4.1
  - PLONE=4.2
  - PLONE=4.3
python:
- 2.6
- 2.7
language: python
before_script:
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bin/test
matrix:
  exclude:
  - env: PLONE=4.0
    python: 2.7
  - env: PLONE=4.1
    python: 2.7
  - env: PLONE=4.2
    python: 2.6
  - env: PLONE=4.3
    python: 2.6
