language: python
python:
  - 2.6
  - 2.7
before_install:
  - sudo apt-get update
# apt-get update is needed as there's a faulty PPA in use inside travis
# itself, which means we cannot install git-svn. The update fixes it.
  - sudo apt-get install git-svn
# In the line above, really only git-svn is needed as the rest
# is automatically installed. But then again, git-svn used to be
# installed by default, too. So for later reference, you need
# "git bzr mercurial subversion", too.
notifications:
  irc:
    channels: "irc.freenode.org#vanrees"
    on_success: change
env: HGUSER=temp
install:
  - python bootstrap.py
  - bin/buildout
  - git config --global user.name "Temp user"
  - git config --global user.email "temp@example.com"
  - bzr whoami "Temp user <temp@example.com>"
script:
  - bin/test
