---
- name: restart sshd
  action: service name=ssh state=restarted
  only_if: $is_debian_or_ubuntu

- name: restart sshd
  action: service name=sshd state=restarted
  only_if: $is_centos

- name: restart iptables
  action: service name=iptables-persistent state=restarted
  only_if: $is_debian_or_ubuntu

- name: restart iptables
  action: service name=iptables state=restarted
  only_if: $is_centos

- name: reload exports
  action: shell exportfs -r

- name: ensure nfs service is running
  service: name=nfs-kernel-server state=started
  only_if: $is_debian_or_ubuntu

- name: ensure nfs service is running
  service: name=nfs state=started
  only_if: $is_centos

