__version__ = "0.0.6"
__git_commiter_name__ = "Tal Yalon"
__git_commiter_email__ = "tal.yalon@gmail.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '64657878be642f0ba299aee7c00430373b891625'
__git_head_subject__ = 'HOSTDEV-969 fixed'
__git_head_message__ = ''
__git_dirty_diff__ = ''