language: python
python:
  - 2.7

env:
  global:
  - secure: |-
      lKBuylDkHj39RmhNjJPMMfwD+BxcwYkpRmGSGQ6orIfj8/OZN/semVuUW8KG
      FNEBtbJ6UEhdl6C/8WiTx+BJafflLng1K8motOZAXRbSshB0vufXvSgIfoNB
      CzYcw8pfkIHELVPFapKp7gNEASiw4zZPZwloJIGywJf6jsD7Fas=  # coveralls token

install:
 - $(which echo) -e "[buildout]\nextends = buildout.d/travis.cfg" > buildout.cfg
 - make .installed.cfg

script:
 - make coverage

after_success:
 - pip install python-coveralls==2.4.0
 - coveralls

notifications:
  irc:
    - "irc.freenode.org#niteoweb"

deploy:
    provider: heroku
    strategy: git
    api_key:
    - secure: |-
        FdsMH2lEnRKILH2n9r656x1KHkTOqFpsRen4IohT4k7x9znuwzpDxTEecBjn
        4t3XE7vnRO4skks5VLYAiwCmuCI3kJIzbn+E5J480pwuQcR1U3t3PkzmHl0v
        vHdlbBnVgSCIP0sR+jP6WXXG7wXHVUFX9A+02SLJXedAsge5kyY=  # heroku api key
    app:
        master: zuluapp
        staging: zuluapp-staging
