
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.2-4-g899d4d7'
version_full = '899d4d74c93016f907d43551972e66fcb7b86262'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

