# -*- coding: utf-8 -*-

EMAIL_MESSAGE_STATUS_DRAFT = 1
EMAIL_MESSAGE_STATUS_TO_BE_DISPATCHED = 2
EMAIL_MESSAGE_STATUS_RUNNING = 3
EMAIL_MESSAGE_STATUS_SUSPENDED = 4
EMAIL_MESSAGE_STATUS_DONE = 5

EMAIL_TRANSACTIONAL_EMAIL_MESSAGE_TYPE = 1
EMAIL_NEWSLETTER_MESSAGE_TYPE = 2


RECIPIENT_STATUS_TO_BE_SENT = 1
RECIPIENT_STATUS_DISPATCHED = 2
RECIPIENT_STATUS_SENDING = 3
RECIPIENT_STATUS_WONT_SEND = 4
RECIPIENT_STATUS_SENT = 5
RECIPIENT_STATUS_NOT_SENT = 6
RECIPIENT_STATUS_BOUNCED = 7
RECIPIENT_STATUS_TRACKED = 8

RECIPIENT_FROM_CONTEXT_VAR = "FROM"
RECIPIENT_FROM_NAME_CONTEXT_VAR = "FROM_NAME"
RECIPIENT_REPLY_TO_CONTEXT_VAR = "REPLY_TO"
RECIPIENT_REPLY_TO_NAME_CONTEXT_VAR = "REPLY_TO_NAME"


SES_IDENTITY_VERIFICATION_PENDING = 1
SES_IDENTITY_VERIFICATION_SUCCESS = 2
SES_IDENTITY_VERIFICATION_FAILED = 3
SES_IDENTITY_VERIFICATION_TEMPORARY_FAILURE = 4
SES_IDENTITY_VERIFICATION_DOES_NOT_EXIST = 0  # added for completness
