
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.1'
version_full = '3f6fe9e4b57e9c7a8ed5a9ece8e316bdee0d2806'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

