language: python
python:
  - "2.7"
# command to install dependencies
before_install: "sudo apt-get install -y libzmq3-dev libevent-dev"
install: 
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r test-requirements.txt --use-mirrors"
  - "python setup.py develop"
# command to run tests
script: "./.unittests"