session_name: tmuxp
windows:
- window_name: tmuxp
  layout: main-horizontal
  options:
    main-pane-height: 50
  start_directory: ./
  shell_command_before: source .env/bin/activate
  panes:
  - shell_command: 
    - vim
    - :Ex
    focus: true
  - shell_command: 
    - cowsay hi
  - shell_command: 
    - nodemon -e py --exec 'python' run_tests.py
- window_name: docs
  layout: main-horizontal
  options:
    main-pane-height: 50
  start_directory: ./
  automatic_rename: true
  shell_command_before: 
    - cd ./doc
    - source .env/bin/activate
  panes:
  - shell_command:
    - vim
    focus: true
  - pwd
  - shell_command:
    - cd _build/html
    - python -m SimpleHTTPServer
  - nodemon -e py,rst --exec 'make html'
