before_install:
  - sudo apt-get update -qq || true
  - sudo apt-get --reinstall install -qq language-pack-en language-pack-es
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - "pip install -r requirements-tests.txt --use-mirrors"
  - "pip install . --use-mirrors"
# We run tests, nikola (to see if the command is executable) and flake8.
script:
  - nosetests --with-coverage --cover-package=nikola --with-doctest --doctest-options=+NORMALIZE_WHITESPACE --logging-filter=-yapsy
  - nikola help
  - "flake8 --ignore=E501 ."
after_success:
  - coveralls
notifications:
  irc:
    channels:
      - "chat.freenode.net#nikola"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view: %{compare_url}"
      - "Build details: %{build_url}"
