# Valid values: 'none', 'debug', 'info', 'warning', 'error', 'critical'
loglevel: warning
plugins: [combine, autorotate, scantailor, pdfbeads]

# Options for devices
device:
    sensitivity: 80
    shutter_speed: 1/25
    zoom_level: 3
    dpi: 300

# Options for 'capture' step
capture:
    # Keys that trigger a capture. Put the space bar inside double ticks.
    capture_keys: [" " , b]

# Options for 'download' step
download:
    # keep files on devices after downloading
    keep: no

# Rotation applied to images from left and right device in degrees,
# can be positive or negative
autorotate:
    left: -90
    right: 90

colorcorrect:
    true_red: 119
    true_green: 119
    true_blue: 119

# ScanTailor options, see `scantailor-cli --help`
scantailor:
    # Don't prompt user for manual inspection of settings
    autopilot: no
    rotate: no
    split_pages: yes
    deskew: yes
    content: yes
    margins: yes
    # Can be 'content' or 'page'
    detection: content
    margins: [2.5, 2.5, 2.5, 2.5] # top, right, bottom, left

    content_detection: normal # not yet implemented
    auto_margins: no # not yet implemented
    output_dpi: auto # not yet implemented
    color_mode: black_and_white # not yet implemented
    binarize_threshold: 0 # not yet implemented
    despeckle: normal # not yet implemented
    dewarp: no # not yet implemented

# PDF output options, see `pdfbeads --help`
pdfbeads:
    layout: SinglePage # not yet implemented
    mask_compression: jbig2 # not yet implemented
    jbig2_dict_size: 15 # not yet implemented
    bg_compression: jp2 # not yet implemented

# DJVU output options, see `djvubind --help`
djvubind:
    ocr: none
    tesseract_options: [] # not yet implemented
    cuneiform_options: [] # not yet implemented
