
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.4'
version_full = 'fcb93701a44eca38ce526fa8618b7e706d744765'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

