__version__ = "0.1.6"
__git_commiter_name__ = "Tal Yalon"
__git_commiter_email__ = "tal.yalon@gmail.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = 'c66209bc9b1fed2f59fc3b0a7344b26253664da6'
__git_head_subject__ = "TRIVIAL changed cast to C-cast so scumbag Apple compiler won' 't shout"
__git_head_message__ = ''
__git_dirty_diff__ = ''