/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "plow_constants.h"

namespace Plow {

const plowConstants g_plow_constants;

plowConstants::plowConstants() {
}

} // namespace

