
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.2-3-ga114a00'
version_full = 'a114a0003695ed8a31277b83f99dd64a100988ed'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

