language: python
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=pypy
install:
    - sudo apt-get install enscript
    - pip install tox
script:
    - tox
notifications:
    email: false
