
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.7'
version_full = 'd51d6bedfecd41491f2c8243235e7d3db043a4d7'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

