language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
install:
  - pip install -e .
  - pip install -r tests/requirements.txt
  - pip install https://github.com/django/django/archive/${DJANGO}.zip#egg=django
script:
  - inv test
env:
  - DJANGO=1.4.6
  - DJANGO=1.5.2
  - DJANGO=stable/1.6.x
matrix:
  exclude:
    - python: 3.2
      env: DJANGO=1.4.6
    - python: 3.3
      env: DJANGO=1.4.6
branches:
  except:
    templates/1.5.x
    templates/1.6.x
