XBEM_BUILD_NAMESPACE = "http://xslc.org/XBEM/Build"
XBEM_DECL_NAMESPACE = "http://xslc.org/XBEM/Declaration"
XBEM_DEP_NAMESPACE = "http://xslc.org/XBEM/Dependency"
XBEM_REPO_NAMESPACE = "http://xslc.org/XBEM/Repository"
XBEM_BLOCK_NAMESPACE = "http://xslc.org/XBEM/Block"
XBEM_ELEMENT_NAMESPACE = "http://xslc.org/XBEM/Element"
XBEM_MODIFIER_NAMESPACE = "http://xslc.org/XBEM/Modifier"
