
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.1.7'
version_full = 'e44228bac393cfc76d56f68e0507c8f26959205f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

