
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.1.4'
version_full = 'fe5a5fbe43de840a17c6966c8689aa591f17722c'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

