language: python
python:
  - 2.7
# command to run tests
script:
  # for now, install cherrypy manually until it can be resolved by ptr
  - easy_install -f https://bitbucket.org/cherrypy/cherrypy/downloads "cherrypy>=3.2.3dev-20121007,<3.3dev"
  - python setup.py ptr
