
# This file was generated by 'versioneer.py' (0.7) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.1.13'
version_full = '5a0f714827ed84dd2589064f7dbd19e22f3e509d'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

