---
# This playbook contains common plays that will be run on all nodes.
- name: set host name
  template: src=hostname.j2 dest=/etc/hostname
  notify:
  - update hostname

- name: add multiple network interfaces 
  template: src=interfaces.j2 dest=/etc/network/interfaces
  notify:
  - restart networking service
