
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.3'
version_full = '440a79fb330ffda37ed987cdc7e74333ed99266f'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

