language: python

install:
  - python bootstrap.py
  - ./bin/buildout

script:
  - ./bin/zeo start && ./bin/zeopack -vv && ./bin/zeo stop
  - ./bin/zeo start && ./bin/zeopack -vv && ./bin/zeo stop
  - ./bin/zeo start && ./bin/zeopack -vv && ./bin/zeo stop

