
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.4.0'
version_full = '26e02c914fb5f626d5c802ea86c7f1ea77d2287d'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

