
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.1.5'
version_full = '22b88ec71e02df826eb1b4a75444d3bc64ce60dc'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

