
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.5'
version_full = '5be557db1e5eff7fec71e1c65b0cbb4cb54c2ba6'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

