__version__ = "0.3.32"
__git_commiter_name__ = "Arnon Yaari"
__git_commiter_email__ = "arnony@infinidat.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '49cb50319e9a4730c8cb0d0692070b03de8fa5f8'
__git_head_subject__ = 'fix tests'
__git_head_message__ = ''
__git_dirty_diff__ = ''