
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '1.1.6'
version_full = '42e63810462534dec95c3b8dd7b06736253c51f7'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

