
# This file was generated by 'versioneer.py' (0.8+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.0'
version_full = '0fb798aedde04bd8f4ad4f04b6a406ea8713cbbb'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

