---
- name: configure ppa
  action: apt_repository repo=ppa:semiosis/ubuntu-glusterfs-3.3
  only_if: $is_ubuntu
  tags:
    - gluster

- name: configure GlusterFS repository
  action: template src=gluster/templates/etc/yum.repos.d/gluster.repo.j2 dest=/etc/yum.repos.d/gluster.repo
  only_if: $is_centos
  tags:
    - gluster

- name: Install glusterfs client
  action: apt name=glusterfs-client state=installed update_cache=yes
  only_if: $is_ubuntu
  tags:
    - gluster

- name: Install glusterfs packages (CentOS)
  action: yum name=$item state=installed
  with_items:
    - glusterfs-client
  only_if: $is_centos
  tags:
    - gluster

- name: Create mountpoing
  action: file path=/glusterfs state=directory
  tags:
    - gluster

- name: Mount the glusterfs filesystem
  action: mount name=/glusterfs fstype=glusterfs src=${groups.gluster_data[0]}:${gluster_volume} state=mounted
  tags:
    - gluster
