
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.1-3-g5a14811'
version_full = '5a148119309f82b9b2c507bb28d3d864fa418977'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

