
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.2'
version_full = '6a72835b3fa7267ffcf30ae0e5b5fa948e296390'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

