__version__ = "0.1"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.1)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '362aa855ff3e8fd712571d8b55e6cf9701138a5c'
__git_head_subject__ = 'Finished release v0.1.'
__git_head_message__ = '* release/v0.1:\n  buildout.cfg: changed isolated python version to v2.7.5.4\n  TRIVIAL monotonic_time\n  added all project files'
__git_dirty_diff__ = ''