__version__ = "0.0.8"
__git_commiter_name__ = "Tal Yalon"
__git_commiter_email__ = "tal.yalon@gmail.com"
__git_branch__ = '(Not currently on any branch)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '53eecbd460004cb90f590ff5f76918a9a3ebf7f7'
__git_head_subject__ = 'Finished release v0.0.8.'
__git_head_message__ = ''
__git_dirty_diff__ = ''