
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.4'
version_full = '66abb4ed550ab7dccb73d5064777ea0c02187e25'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

