
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.6-2-g00fcda5'
version_full = '00fcda57c933d68df8a52d9769246a81e83d0792'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

