language: python
python:
    - "2.7"
    - "2.6"
install:
    - pip install https://github.com/downloads/SiteSupport/gevent/gevent-1.0rc2.tar.gz
    - pip install twisted>=12.0 --use-mirrors
    - pip install pyzmq==13.0 --use-mirrors
    - pip install genshi --use-mirrors
script:
    - python setup.py test
