__version__ = "0.0.12"
__git_commiter_name__ = "Guy Rozendorn"
__git_commiter_email__ = "guy@rzn.co.il"
__git_branch__ = '(detached from v0.0.12)'
__git_remote_tracking_branch__ = '(No remote tracking)'
__git_remote_url__ = '(Not remote tracking)'
__git_head_hash__ = '273bc943ced7e65aaa96c3ab457fce48aaf8a4b7'
__git_head_subject__ = 'Finished release v0.0.12.'
__git_head_message__ = '* release/v0.0.12:\n  support overloading of Directory class\n  yet another timestamp format'
__git_dirty_diff__ = ''