
# This file was generated by 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.1-3-ge1f1f50'
version_full = 'e1f1f502c724e6229eb81962c15a6b8cb826a2fa'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

